io.write("Terminal is starting up --- done!\n")
io.write("Making sure everything works --- Done!\n")
io.write("Loading lua files --- Done!\n")
io.write("Loading lualib files --- Done!\n")
io.write("Checking boot --- Done!\n")
io.write("Checking bootcheck --- Done!\n")
io.write("Activating UI work arounds --- Done!\n")
os.execute("python pythonlib/splash/splash.py")
dofile("lualib/utils/secure/login.lua")